### ISSUE TITLE
Support ethgasstation as gasprice oracle

### ISSUE THREAD

**Issue by phahulin** [poanetwork/tokenbridge#105]
Please add support for gasprice oracle provided by https://ethgasstation.info/
API endpoint is
https://ethgasstation.info/json/ethgasAPI.json

The problem with this API is that gasprice values are in 0.1 GWei instead of GWei, so they would have to be divided by 10 before passing to sender.

As @akolotov suggested it would be handy to handle this more generally and introduce a new env variable - numeric (floating point) coefficient that would be multiplied by the value returned from gasprice API.

**Comment by akolotov** [comment]
Correct. We can have such kind of coefficient in the configuration files of the oracle, UI and monitor.

The name of the parameter could be `HOME_GAS_PRICE_FACTOR`.

It could help not only normalize the value from the gas price oracle like EthGasStation (e.g. if `HOME_GAS_PRICE_FACTOR=0.1`) but also could amplify the gas price value for the gas price oracle maintained by the POA project (e.g. `HOME_GAS_PRICE_FACTOR=1.5` will slightly increase speed of including transactions to the block).
