### ISSUE TITLE
Add deployment-oracle testing in CI

### ISSUE THREAD

**Issue by rzadp** [poanetwork/tokenbridge#11]

**Comment by rzadp** [comment]
@akolotov Should we close it having merged #113, and create separate for testing Monitor and UI deployment?

**Comment by akolotov** [comment]
Yes, we can close it as soon as two new issues are created.

**Comment by rzadp** [comment]
Added https://github.com/poanetwork/tokenbridge/issues/129 and https://github.com/poanetwork/tokenbridge/issues/130
