### ISSUE TITLE
Extend monitor E2E tests

### ISSUE THREAD

**Issue by rzadp** [poanetwork/tokenbridge#115]
- [x] Test that it works for the 3 bridge modes
- [ ] Check that some attributes are present on the data served
- [ ] Preferably rewrite to JS+mocha

**Comment by rzadp** [comment]
@akolotov @patitonar Do you think that it is desirable to rewrite `monitor-e2e` from bash to JS+mocha, like `ui-e2e` and `oracle-e2e`?

My assessment is that it would pay off if we will keep extending the tests, but maybe it is not worth it if we will only add a couple of cases to check that some attributes are present on the data served, and that's it.

**Comment by patitonar** [comment]
I think it would be nice to have the monitor e2e tests written in JS. For now is possible we have simple test cases but if eventually the monitor could be extended with some of the features described [here](https://github.com/poanetwork/tokenbridge/issues/32), I think it would be easier to extend the tests if they are in JS.
