### ISSUE TITLE
Ultimate E2E tests

### ISSUE THREAD

**Issue by rzadp** [poanetwork/tokenbridge#121]
We should combine the molecule tests with e2e tests into ultimate e2e tests:

- Deploy the contracts using e2e-commons
- Deploy Oracle/UI/Monitor using Molecule, using the above contracts
- Run oracle-e2e, ui-e2e and monitor-e2e testing the above

**Comment by akolotov** [comment]
I would prefer to have step-by-step (PR-by-PR) introduction of components in the ultimate test.
And first of all, we need to by deployment e2e testing we need to check whether Ansible prepares proper configuration for the service. For this poaservice (the oracle) needs to be run to communicate to a real contracts.

**Comment by rzadp** [comment]
The 3 types of bridge, and 3 components form a table of 9 cases to take care of.
I created the table to track progress:

... | `native-to-erc` | `erc-to-erc` | `erc-to-native`
--- | --- | --- | ---
**`oracle-e2e`** | ✅ Done | TODO | TODO
**`ui-e2e`** | TODO | TODO | TODO
**`monitor-e2e`** | TODO | TODO | TODO
