### ISSUE TITLE
Tests do not handle forked Pull Requests

### ISSUE THREAD

**Issue by rzadp** [poanetwork/tokenbridge#167]
The first PR https://github.com/poanetwork/tokenbridge/pull/166 to the monorepo from a forked repository revealed that the deployment tests do not handle such kind of PRs.

The reason is that the deployment playbooks use `git pull`, and in order to test the deployment together with changes to codebase on a given branch, we pull "current branch".
But the "current branch" does on exist on our monorepo, it only exists on a forked repo - so `git pull` fails.

**Comment by rzadp** [comment]
At the moment I don't have a good idea on how to handle this.
I guess one way would be to pull "current repo", in addition to "current branch"

@ArseniiPetrovich @phahulin @akolotov Do you have some idea on how to handle it?

**Comment by rzadp** [comment]
I can think of another way to approach this - change the playbooks.

Instead of doing a `git pull` task, we would just use a task to `copy` the files we have locally.
Since locally we have just the files we want to test.
And also it would remove the need to `git push` first.

**Comment by phahulin** [comment]
I think it's a good idea to just copy the files :+1:

**Comment by akolotov** [comment]
correct. but we need to make sure that 
1) all files are added to the index
2) only added files are copied
It could prevent cases when the local tests are performed well but failed when the changes are pushed to the remote repo
