### ISSUE TITLE
Move molecule to root directory

### ISSUE THREAD

**Issue by rzadp** [poanetwork/tokenbridge#175]
In `deployment` we have the deployment playbooks, and in `deployment/molecule` we have molecule tests for deployment.

In order to follow flat structure of the monorepository, I think it would be nice to move `deployment/molecule` to root directory, and add it to [Structure](https://github.com/poanetwork/tokenbridge#structure)

**Comment by rzadp** [comment]
@akolotov Do you agree?

**Comment by akolotov** [comment]
It is OK for me. But is it better to call it `deployment-e2e` since this name describes the content of the directory better?

**Comment by rzadp** [comment]
> It is OK for me. But is it better to call it `deployment-e2e` since this name describes the content of the directory better?

I agree.
