### ISSUE TITLE
Update UI-E2E for recent version of Chrome

### ISSUE THREAD

**Issue by rzadp** [poanetwork/tokenbridge#184]
Running `ui-e2e` on device with up-to-date version of Chrome errors out with:
`SessionNotCreatedError: session not created: Chrome version must be between 71 and 75`

The fix on CI was to install out-dated version of Chrome. We should update `ui-e2e` so that it is possible to run the tests with up-to-date Chrome (if possible).

**Comment by akolotov** [comment]
Should the `ui-e2e` tests be run within the docker session on any device?

**Comment by rzadp** [comment]
If something goes wrong, and there is a need to debug the tests, it would
be difficult or impossible to debug without seeing the chrome window on
one’s device.. unless there is some way to do it that I am not aware of
