### ISSUE TITLE
Develop a procedure to upgrade the oracle

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge#203]
At this moment there is no official published procedure that will help users to upgrade existing setups of the TokenBridge oracle.

This issue is being created to reflect in the documentation the following upgrade paths:
1. an ancient release of [the oracle from the standalone repo](https://github.com/poanetwork/token-bridge) provisioned with [the deployment playbooks](https://github.com/poanetwork/deployment-bridge)
2. a previous snapshot of the tokenbridge toolkit provisioned from the monorepo to a newer one

**Comment by akolotov** [comment]
@phahulin hi Pavel, currently the tokenbridge has no developed procedure to perform migration from the previous releases without necessity to run another (virtual or real) system. Could you take at this issue and prepare a set of documents how to existing nodes could be upgraded? Most probably the migration will also require some changes in the deployment scripts. Thanks!

**Comment by phahulin** [comment]
Which tokenbridge versions are we talking about in this issue? Just the ones from current tokenbridge monorepo, or including previous versions too?

**Comment by akolotov** [comment]
In fact two different migration procedures are required:
1. for the upgrade from the oracle that based on the standalone repos of the oracle (the last official release in https://github.com/poanetwork/token-bridge/) and deployment-scripts.
2. for the upgrade from a previous minor release (from `a.b.0` to `a.b+1.0`). So, it should be a general guide how to upgrade the oracle. The token bridge developers will also follow this guide in the future to think of new release with respect to the migration from a previous one. Ideally, we will also have in the future an e2e test which will test the upgrade path.

**Comment by phahulin** [comment]
For p.1, will a document similar to this forum post https://forum.poa.network/t/xdai-bridge-update-for-multi-collateral-dai-migration/3153/2 be ok?

I think it should be possible to reuse an existing system, but the difference in codebase looks significant, so there may be conflicts. I could try to check it and prepare an upgrade guide similar to the forum post above.

**Comment by akolotov** [comment]
> For p.1, will a document similar to this forum post https://forum.poa.network/t/xdai-bridge-update-for-multi-collateral-dai-migration/3153/2 be ok?

My understanding is that this procedure requires two different systems. Is it worth (we have set of partners deployed the bridge from old repos) to invent of an approach that will not require to use two systems and will be more automated?

**Comment by akolotov** [comment]
Instructions to upgrade from a standalone repo were provided here: https://forum.poa.network/t/xdai-bridge-update-for-multi-collateral-dai-migration/3153/2.

Instructions to upgrade from one release of monorepo to another [were provided on the forum](https://forum.poa.network/t/upgrade-the-oracle-of-the-xdai-bridge-to-support-deposits-in-sai-and-dai-tokens/3210).

Further, it is suggested to use the upgrade scripts like [this](https://github.com/poanetwork/tokenbridge/blob/8c2f58b06fa172d700ca178ccdcd6f2d90ed0193/oracle/upgrade/oracle-upgrade-1.1.1-to-1.2.0-rc0.sh) to simplify upgrade procedure.
