### ISSUE TITLE
Extract repeated submodules/poa-bridge-contracts into one in root dir

### ISSUE THREAD

**Issue by rzadp** [poanetwork/tokenbridge#21]
Release 2.3.0-rc0 should be used for poa-bridge-contracts.

**Comment by akolotov** [comment]
I would add even more - instead of usage of ABI sourced in the `token-bridge/abis` directory it is necessary to compile them from the contract submodule. By doing this we will always have updated ABIs without necessity to update them manually every time when the contracts are being changed.

**Comment by akolotov** [comment]
In order to not mix the work let's consider this issue to
- [ ] introduce the git submodule for the bridge contracts in the root dir
- [ ] change the oracle and UI projects as so this submodule is used for e2e tests (this is only the place where the contract submodule is used now).

**Comment by rzadp** [comment]
Fully finishing this is blocked on #52 and #53
