### ISSUE TITLE
ERC-to-ERC with different recipient on other side of the bridge

### ISSUE THREAD

**Issue by LiorRabin** [poanetwork/tokenbridge#218]
Hello,
Is there any plan or suggestion on how to implement moving ERC tokens between two networks but with a different recipient on the other side of the bridge?
We're thinking of using ERC677 `data` param for the recipient address and modifying the bridge oracle accordingly.
Any thoughts?

**Comment by akolotov** [comment]
@LiorRabin hi! Thanks for the question.
I already prepared a suggestion for this [topic on the forum](https://forum.poa.network/t/alternative-receiver-for-tokenbridge-transfer-operations/3025/). You could provide your comments there.

So far, I heard no objections so this feature is our next item to do as soon as we finish with the preparation of [demo for transferring Cryptokitties between chains by using Arbitrary Message Bridge](https://github.com/poanetwork/cryptokitties-xdai-demo/projects/1).

**Comment by LiorRabin** [comment]
Hi @akolotov, I will definitely take a look! Thanks

**Comment by LiorRabin** [comment]
@akolotov it looks like something we need as well - I already implemented it in a way on our version of POA's contract & oracle repositories.
You can see my PRs here and comment on how/if it serves your purpose as well.
https://github.com/fuseio/bridge-contracts/pull/5
https://github.com/fuseio/bridge-oracle/pull/4

**Comment by akolotov** [comment]
Thanks, I have added a comment there related to the general approach: logic in contracts VS logic in the oracle
