### ISSUE TITLE
Poa bridge contracts not working on node >= 10

### ISSUE THREAD

**Issue by rzadp** [poanetwork/tokenbridge#22]
I had to downgrade my node version to 9 in order to perform `npm install` in poa-bridge-contracts repo.

![Screenshot 2019-05-07 at 14 06 52](https://user-images.githubusercontent.com/12039224/57298006-636bdd80-70d1-11e9-9c8a-29cb735dfbe8.png)

**Comment by akolotov** [comment]
Please make sure that you are using the contracts from https://github.com/poanetwork/poa-bridge-contracts/releases/tag/2.3.0-rc0.

**Comment by rzadp** [comment]
> Please make sure that you are using the contracts from https://github.com/poanetwork/poa-bridge-contracts/releases/tag/2.3.0-rc0.

I was using `master`. It works on `2.3.0-rc0`. I've put in the description of #21 to use this release.
