### ISSUE TITLE
Support metamask breaking changes in new API

### ISSUE THREAD

**Issue by patitonar** [poanetwork/tokenbridge#229]
Breaking changes are listed in this post https://medium.com/metamask/breaking-changes-to-the-metamask-inpage-provider-b4dde069dd0a

The only change that seems to affect the Bridge-UI component is: 
- Stop reloading the page on network change

A [possible solution](https://medium.com/metamask/no-longer-reloading-pages-on-network-change-fbf041942b44) is to emulate the current behavior by subscribing to `chainChanged` event and trigger a reload

```javascript
ethereum.on('chainChanged', () => {
  document.location.reload()
})
```
when we detect the `ethereum` injected object 
https://github.com/poanetwork/tokenbridge/blob/8b010f887dbe9c369e3f30cf9ea0d3a59c83fe25/ui/src/stores/utils/web3.js#L29-L41

**Comment by akolotov** [comment]
@patitonar thanks for analysis. Are we already using a generic `web3.js` rather than the instance provided by MetaMask?

**Comment by varasev** [comment]
We can just set `window.ethereum.autoRefreshOnNetworkChange = true`.

**Comment by patitonar** [comment]
@akolotov We are using our own `web3.js` version, that uses the provider injected by Metamask.

@varasev I don't think we would be able to use `window.ethereum.autoRefreshOnNetworkChange` since it will be [removed in the new API](https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#ethereum.autorefreshonnetworkchange-(to-be-removed)).

Metamask will start supporting the [new API](https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#new-api) in `v7.6.0`, slated for release during the week of **November 25, 2019**. At that point, it will support the old and new API until **December 16**, after which only the new API will be supported. 

Once Metamask `v7.6.0` is released we will be able to implement and correctly test the required changes in our code

**Comment by varasev** [comment]
@patitonar Got it, thanks. Let's use your proposed solution then.

**Comment by akolotov** [comment]
As per [the information from MM team](https://medium.com/metamask/breaking-changes-to-the-metamask-inpage-provider-b4dde069dd0a) the new inpage provider is planned for Q1 of 2020. No exact date yet.

**Comment by aminlatifi** [comment]
We started to supporting metamsk changes in our dapp. But `send` method does not return promise!
It's our code 
```
  enablePromise = new Promise((resolve, reject) => {
    const promise = window.ethereum.send('eth_requestAccounts');
    promise
      .then(addrs => {
        this.isEnabled = true;
        resolve(addrs);
      })
      .catch(e => {
        enablePromise = false;
        this.isEnabled = false;
        console.log('enable error', e);
        reject(e);
      });
  });
```
It seems it still calls previous (deprecated) send function. Somewhere in documents it's mentioned that the changes will be available on november 25. So I should be able to use them now.

**Comment by akolotov** [comment]
Should we actualize if the planned changes are still needed? If so, consider it to be implemented as part of preparation the UI to STAKE token bridging.
