### ISSUE TITLE
xDAI bridge does not restart after long-term downtime

### ISSUE THREAD

**Issue by ArseniiPetrovich** [poanetwork/tokenbridge#232]
There was a bug in a `containerd` version which caused Docker to fail running containers without any proper notification. As a result, Protofire's xDAI bridge was down for pretty long period of time before we noticed the issue.
Once `containerd` issue was fixed, the bridge restarted, but two of its containers (`bridge_request` and `bridge_affirmation`) falled into endless restart cycle.
Four hours after the restart the `bridge_request` module stabilized, but `bridge_affirmation` is still in the loop.
Attaching the `bridge_affirmation` log of one of the cycles for more details:
https://gist.github.com/ArseniiPetrovich/68ec6f14d86775d4dca79a8b0fbc2277

**Comment by akolotov** [comment]
Gerardo (@patitonar) please take a look at the issue.

**Comment by patitonar** [comment]
From the logs it looks like it founds `227 Transfer events` to process and after ~20 seconds of processing most of them the error `Max processing time reached` appears which causes to stop the app. Then docker restart the app and this behavior repeats.

@ArseniiPetrovich Please try increasing the value in the parameter `ORACLE_MAX_PROCESSING_TIME` or `MAX_PROCESSING_TIME` (it depends on the version of the oracle), that would give the oracle more time to finish processing the events

**Comment by ArseniiPetrovich** [comment]
@patitonar Is it a variable in `.env` file? I don't have it in mine. I can add, but what value should I set?

**Comment by patitonar** [comment]
Yes, it is a variable in `.env` file. 

This is the logic for this param: 
https://github.com/poanetwork/token-bridge/blob/master/config/base.config.js#L48-L56

If it is not set, the value will be 
```
4 * Math.max(process.env.HOME_POLLING_INTERVAL, process.env.FOREIGN_POLLING_INTERVAL)
```
so it should be bigger than that.

I don't know which are the values set for `HOME_POLLING_INTERVAL` and `FOREIGN_POLLING_INTERVAL`, does 60 seconds (`MAX_PROCESSING_TIME=60000`) look like a good possible value?

**Comment by ArseniiPetrovich** [comment]
Works like a charm!
