### ISSUE TITLE
Update deployment-bridge after introducing into the monorepo 

### ISSUE THREAD

**Issue by rzadp** [poanetwork/tokenbridge#24]
- [x] Rename `deployment-bridge/bridge-nodejs` to `deployment-bridge/oracle`
- [x] Rename `deployment-bridge` to `deployment`
- [x] General `Bridge overview` section will be extracted as part of #23 
- [x] Introduce ansible-lint, check linting on CI
- [ ] Update links to Github repos and folder names in `deployment-bridge/bridge-nodejs/README.md`
- [x] Remove legacy `deployment-bridge/upgradable-wo-parity`
- [x] Update `Structure` section in root readme

**Comment by akolotov** [comment]
Please add to remove `upgradable-wo-parity` since it is a legacy code from ages when we had Rust version of the oracle and definitely will not relate to this monorepo
