### ISSUE TITLE
Proper bridge balance calculation in the UI if Chai token is used

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge#283]
As soon as poanetwork/tokenbridge-contracts#356 is merged it is necessary to modify the method of UI which is used to calculate the xDai bridge balance ("_Totally minted by the bridge_") on the statistic page (e.g.https://dai-bridge.poa.network/statistics). With the mentioned changes in the bridge contracts it could be possible situation when the entire bridge balance is the sum of three balances: Sai, Dai and Chai. So, the label "_Totally minted by the bridge_" must operates with the sum of these tokens balances.

**Comment by k1rill-fedoseev** [comment]
If I understood this correctly, there is no need to modify anything in the UI component.
Look:
https://github.com/poanetwork/tokenbridge/blob/bc6dd131939f5995d3e1ee95843026ad9ddf5134/ui/src/stores/HomeStore.js#L244-L263
Here, for `ERC_TO_NATIVE` bridge mode, we use xDai's `blockReward.mintedTotallyByBridge() - homeBridge.totalBurntCoins()` for estimation of total amount of bridged DAI tokens.
Operations with Chai token on the ETH Mainnet side does not change anything on the xDai side.

**Comment by akolotov** [comment]
Sorry. I missed this update. Thanks for investigation! Closing the issue.
