### ISSUE TITLE
Improve displayed information about validator operation status when no transactions are found

### ISSUE THREAD

**Issue by patitonar** [poanetwork/tokenbridge#391]
There are moments after the validator finished waiting for block confirmations when there is not data about a success/failed/pending transaction and so the app displays a loading icon in the status of the validator. It makes sense to look for ways to give better information on the current situation

**Comment by patitonar** [comment]
Here are some options that we can consider for the scenario described:
- We could add a new status description for this case, something like:
```
Status: Waiting / Confirmation Waiting (depending on direction)

The specified transaction was included in a block. The app is looking for confirmations. Either
1. Validators are still waiting for chain finalization.
2. Validators are processing the message.
3. Validators are not active.
Check status again after a few blocks. If the issue still persists contact to the validators by messaging on https://forum.poa.network/c/support
```
- Only for this scenario replace the loading Icon in the Age field with some text like `Searching transaction...` so it's clear that we are still looking for information

With these two options, the app will look like this
![searching](https://user-images.githubusercontent.com/4614574/87694451-9c3b2400-c764-11ea-902f-ec6d0318d43b.png)

What do you think @akolotov ?

**Comment by akolotov** [comment]
Thanks @patitonar for detailed explanation!

Does it mean that we need to introduce a new state between 1 and 2?

First of all, I would get rid of the loading icon at all and consider to display a validator status explicitly (waiting, pending etc.).

Then, yes, we need a description for the situation you pointed out. I would re-phrase the text as the following:
```
The specified transaction was included in a block. Either
1. Validators are waiting for chain finalization before sending their signatures.
2. Validators are not active.
3. The bridge was stopped.
Check status again after a few blocks. If the issue still persists contact to the validators by messaging on https://forum.poa.network/c/support
```

And the third thing is that it makes sense to add the phrase "Check status again after a few blocks. If the issue still persists contact to the validators by messaging on https://forum.poa.network/c/support" in the state 2 description as well for the cases when only part of validators are not active.
