### ISSUE TITLE
Waiting for a validator displayed for overall Success status

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge#409]
It was found that the ALM reports the status "Waiting" for one of the validators even if the entire status of the transaction is "Success"

https://alm-demo-e0998.web.app/42/0x93d61fc1d6abdafe99d4df0e35b84cda2517401c35f7f739ae458616f68955d8

![image](https://user-images.githubusercontent.com/20793260/88476271-ce583d00-cf3f-11ea-91dc-3fb5132b19f1.png)

**Comment by officialmike7** [comment]
Same is true for transactions on https://bridge.energyweb.org/
EWT is not converting to EWTB, it gets stuck at the exact same point as the above^ (e.g. "Waiting" for one of the validators even if the entire status of the transaction is "Success")

**Comment by akolotov** [comment]
> Same is true for transactions on https://bridge.energyweb.org/
> EWT is not converting to EWTB, it gets stuck at the exact same point as the above^ (e.g. "Waiting" for one of the validators even if the entire status of the transaction is "Success")

Sorry, but we don't support this bridge. It was deployed independently by the Energy Web project. So, the best way is to communicate to that team by using the social media links provided at https://www.energyweb.org/technology/token/. 

Another point is that the issue was opened against the incorrect logic in displaying the status of the validator in the AMB Live Monitoring tool where as you present the Bridge UI -- they are two different applications for different purposes.
