### ISSUE TITLE
Warn user if deposit/withdrawal could hit the daily limit

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge#434]
The current UI for the xDai bridge does not warn users that the Dai deposit from the Ethereum Mainnet to the xDai chain could hit the daily limit. So, if the user sends transaction it could stuck unhandled for one day. Consider to add the warning in the confirmation window:

![image](https://user-images.githubusercontent.com/20793260/93758260-c26fbb00-fc10-11ea-94c8-488b113b7786.png)

Even if it very unlikely that the withdrawal of the funds could be also stuck, the similar warning should be added if the transfer is being performed in another direction.

**Comment by k1rill-fedoseev** [comment]
Closing, since the UI is no longer a part of this repository.
