### ISSUE TITLE
Remove dependency on `package-lock.json` in Dockerfiles

### ISSUE THREAD

**Issue by rzadp** [poanetwork/tokenbridge#44]
The Dockerfiles are COPYing `package-lock.json` when building images.
We should remove this dependency, or rely on `yarn.lock` instead.

**Comment by rzadp** [comment]
### Dependencies problem

The Docker build processes rely on sub-repository `package.lock` and `package-lock.json`when installing dependencies.

Our local build process installs dependencies for all sub-repositories at one time, and uses one `yarn.lock` in root directory.

We shouldn't have different methods of installing dependencies locally and when building docker images because it can cause tricky errors.

### Number of Dockerfiles

There is a total of 7 Dockerfiles, plus one in `poa-bridge-contracts`.

![Screenshot 2019-05-14 at 13 06 20](https://user-images.githubusercontent.com/12039224/57694217-6d4e8d00-764b-11e9-9ab6-08301791a6de.png)

Seems excessive and increases complexity.

### Proposed solution

I'm thinking about having one Dockerfile in root directory. It would install dependencies for sub-repositories using main `yarn.lock`, and would be used as a build base for sub-repositories `docker-compose` files.

@akolotov @phahulin @ArseniiPetrovich Do you have any comments on this?

**Comment by akolotov** [comment]
@patitonar could you take a look?

**Comment by akolotov** [comment]
My understanding is that some of these docker files are used for e2e testing only, whereas others are to build images used in production. @patitonar please correct me if I am wrong.

**Comment by patitonar** [comment]
> We shouldn't have different methods of installing dependencies locally and when building docker images because it can cause tricky errors.

I agree on this, we should use `yarn` only.

Regarding the Dockerfile most of them are use for e2e testing and can be replaced by accessing the sub-repository needed or be unified in the case of the repeated Parity nodes Dockerfile used on e2e tests. I think the only one used for build for production along with the docker-compose file are the one from the oracle sub-repository
