### ISSUE TITLE
Missing cors header in bridge-common.energyweb.org

### ISSUE THREAD

**Issue by simon-jentzsch** [poanetwork/tokenbridge#496]
On https://bridge.energyweb.org/ when trying to fetch the gasprice during tx preparation I get an error. The console shows me why:

![image](https://user-images.githubusercontent.com/10868622/101356338-36c50c80-3898-11eb-80bd-1bf5b12e88e1.png)

**Comment by akolotov** [comment]
Please use social links on https://www.energyweb.org/ to communicate to the EnergyWeb team to solve this issue. This repo is not intended to address issues of a particular deployment made by a 3rd party team.
