### ISSUE TITLE
COMMON_HOME_GAS_PRICE_SUPPLIER_URL

### ISSUE THREAD

**Issue by wenchaopeng** [poanetwork/tokenbridge#523]
Hi:
        if I want to build a token bridge or AMB in ETH-BSC or ETH-HECO, how do I fill in the `COMMON_HOME_GAS_PRICE_SUPPLIER_URL` in the configuration file?

**Comment by akolotov** [comment]
> Hi:
> if I want to build a token bridge or AMB in ETH-BSC or ETH-HECO, how do I fill in the `COMMON_HOME_GAS_PRICE_SUPPLIER_URL` in the configuration file?

You could skip both `COMMON_HOME_GAS_PRICE_SUPPLIER_URL` and `COMMON_HOME_GAS_PRICE_SPEED_TYPE` in the configuration file.
