### ISSUE TITLE
Update oracle-e2e to work with contracts at 2.3.0-rc0

### ISSUE THREAD

**Issue by rzadp** [poanetwork/tokenbridge#53]
Currently they only work with with `2.2.0`

**Comment by akolotov** [comment]
Details what it is necessary to be done to migrate e2e testing to the next version of contracts provided here: https://github.com/poanetwork/tokenbridge/pull/54#issuecomment-494788260

**Comment by akolotov** [comment]
The [new release v2.3.0](https://github.com/poanetwork/poa-bridge-contracts/releases/tag/2.3.0) of the TokenBridge contracts has been released
