### ISSUE TITLE
Remove UI components from the repository 

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge#547]
The xDAI TokenBridge UI and the OmniBridge UI are kept in a separate repo. The codebase stored in the monorepo is not used in the production any more. Consider to remove the UI from the repo to simplify the codebase and documentation.

**Comment by k1rill-fedoseev** [comment]
Closed via #553

**Comment by q9f** [comment]
Hi, could you point to the new UI repository?
