### ISSUE TITLE
ALM build errors - Type 'Timeout' is not assignable to type 'number'.  TS2322

### ISSUE THREAD

**Issue by daniel-farina** [poanetwork/tokenbridge#597]
Hello guys, 

I'm currently getting this error only on a Ubuntu machine, I don't get it on the local machine (Mac).

```
~/tokenbridge/alm# yarn build
```

```
$ yarn createSnapshots && ./load-env.sh react-app-rewired build
$ node scripts/createSnapshots.js
Creating an optimized production build...
Failed to compile.

/mono/alm/src/hooks/useMessageConfirmations.ts
TypeScript error in /mono/alm/src/hooks/useMessageConfirmations.ts(127,11):
Type 'Timeout' is not assignable to type 'number'.  TS2322

    125 |           setWaitingBlocks(true)
    126 |           setConfirmations(validatorsWaiting)
  > 127 |           timeoutId = setTimeout(checkSignaturesWaitingForBLocks, interval)
        |           ^
    128 |         } else {
    129 |           timeoutId = setTimeout(checkSignaturesWaitingForBLocks, 500)
    130 |         }


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Service 'alm' failed to build : The command '/bin/sh -c yarn run build' returned a non-zero code: 1
```

It seems the compiler is getting confused thinking that timeout is getting called from the browser. Has anyone else gotten this issue? 

It might be related to the fact that tsconfig.json is loading the dom lib, not sure what the purpose is yet. 

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
```
@k1rill-fedoseev  are you getting errors on your end? 

Thank you in advance!

**Comment by k1rill-fedoseev** [comment]
No, I don't see these errors on my side. I can't reproduce it on Mac or Ubuntu, everything is being built successfully.

Could you try running `yarn install` at the `~/tokenbridge` once again?

**Comment by daniel-farina** [comment]
> No, I don't see these errors on my side. I can't reproduce it on Mac or Ubuntu, everything is being built successfully.
> 
> Could you try running `yarn install` at the `~/tokenbridge` once again?

ok so I deleted everything and ran it on a clean folder and it worked. No idea what went wrong there but thanks for verifying on your end!

Closing this! thanks @k1rill-fedoseev
