### ISSUE TITLE
Cross-chain from our blockchain

### ISSUE THREAD

**Issue by damianlluch** [poanetwork/tokenbridge#618]
Hello, I have known about this project because we have been working with the team with blockscout. The question I have is that I see that there are examples of cross-chain between the most popular networks. But, is it possible to cross-chain between our own blockchain and another one, for example, Binance?
We have set up our node with Besu, and we are interested in the project to make a cross-chain but from our blockchain.

Thank you

**Comment by akolotov** [comment]
Yes, it is possible. There is no guidelines so far for this so if you have questions during deployment you can ask them here
