### ISSUE TITLE
Deposited ETH PMA and didnt receive BSC PMA tokens

### ISSUE THREAD

**Issue by altcoindog** [poanetwork/tokenbridge#655]
https://etherscan.io/tx/0x70729fdc32ac4fcb049e0b9ffe9e0414b90235355241dd5b0fa5b63ad9211ff1

**Comment by akolotov** [comment]
It doesn't look like a bridge transaction. Which app url did you use to bridge tokens? The official app is https://omni.gnosischain.com/. The old url is https://omni.xdaichain.com/

**Comment by altcoindog** [comment]
@akolotov 

This is the bridge site i used.
https://bridge.pumapay.io/

this is the documentation
https://docs.pumapay.io/home/pumapay-bridge/

I never received the BSC PMA

**Comment by akolotov** [comment]
This bridge was not deployed by the TokenBridge team. Please find the puma bridge admins and contact to them for the help.
