### ISSUE TITLE
TokenBridge Monitor in the docker environment

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge#77]
Consider to have an option to run the TokenBridge Monitor in the docker container in order to minimize requirements to the system where the monitor could be deployed.

**Comment by rzadp** [comment]
I'm working on dockerizing the monitor, and I'm having a little trouble testing it against locally deployed contracts.

- The `checkWorker.js` script takes ABI from `contracts` and works fine.
- Same for `checkWorker2.js`
- `checkWorker3.js` does not work for me (`VM execution error`). It's using hardcoded ABI from `v1Abis.js` file.

@akolotov @patitonar Could you shed a little light on this? Is `checkWorker3.js` obsolete and should be removed, or should it be updated? It's also missing from the readme.

**Comment by akolotov** [comment]
`checkWorker3.js` works only with v1 bridge contracts. So, you need to use [v1.2](https://github.com/poanetwork/poa-bridge-contracts/releases/tag/1.2) contracts deployed to the test environment. But it also means that you need to use `rust`-based oracle for the bridge. It quite complicates things just to test that legacy stuff works. I would recommend to not test this worker so far.
