### ISSUE TITLE
Display a small help about transfer direction switching

### ISSUE THREAD

**Issue by varasev** [poanetwork/tokenbridge#89]
See https://github.com/poanetwork/bridge-ui/issues/106

**Comment by akolotov** [comment]
Consider to add a drop down list with the list of two chains participating in the bridging similarly it is done for https://voting.poa.network/poa-dapps-voting/.

![image](https://user-images.githubusercontent.com/20793260/80867098-f74b9780-8c9a-11ea-8779-703c98ce843a.png)
