### ISSUE TITLE
Write playbooks for bridge-UI

### ISSUE THREAD

**Issue by rzadp** [poanetwork/tokenbridge#9]

**Comment by rzadp** [comment]
My planned approach for writing this playbook is:
1. Clone the repository to target host
2. Start the `ui` application with `production` environment variable
    - Use `pm2` to manage this process
    - Run the app on port `80`

I imagine an alternative approach would be to:
1. Build the app with `production` env var
2. Copy static `dist` folder to target location supplied by the end client

@akolotov @phahulin @ArseniiPetrovich Do you have any suggestions for this?

**Comment by akolotov** [comment]
Don't you want to run the UI in the docker environment similarly to the oracle?

**Comment by rzadp** [comment]
> Don't you want to run the UI in the docker environment similarly to the oracle?

Oh, yes, right. I want to run the UI (and Monitor) using `docker-compose up -d` much like the Oracle.

**Comment by akolotov** [comment]
So, the most difficult part here is to generate proper environment (e.g. through `.env` file), isn't it?

**Comment by rzadp** [comment]
Seems like it. I'm following the pattern like it's done in the oracle role, so environment setup in `group_vars` with `.env.j2` template
